version: '3.3'
services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
  backend:
    image: gostyaikin/foodgram:v1.0
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
      - docs:/backend/api/docs/
    depends_on:
      - db
    env_file:
      - ../.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/backend/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/usr/share/nginx/html/static/
      - media_value:/usr/share/nginx/html/media/
    depends_on:
        - frontend
        - backend
volumes:
  postgres_data:
  static_value:
  media_value:
