# Generated by Django 2.2.26 on 2022-01-24 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220124_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(through='users.UserSubscription', to=settings.AUTH_USER_MODEL, verbose_name='Subscriptions'),
        ),
    ]
